# Generated by Django 5.0.3 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Items',
            },
        ),

    ]
