# Generated by Django 5.0.3 on 2024-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
