services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my_network
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    depends_on:
      - zookeeper
    networks:
      - my_network
    restart: always

  kafka_consumer:
    build:
      context: ./
    command: python kafka_consumer.py
    depends_on:
      - kafka
    environment:
      - DJANGO_SETTINGS_MODULE=ecomm.settings
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
