"""
Django settings for ecomm project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-n7+!kp5_0edbiii%gly(y0)od=b08_$e6g$gq)i$q6wf6iba_0'

DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'admin_app.app.apps.AdminServiceAppConfig',
    'main_app.apps.EcommAppConfig',
    'storages',
]

DATABASES = {
    'admin_db': {
        'NAME': os.getenv('ADMIN_DB_NAME', 'admin'),
        'USER': os.getenv('ADMIN_DB_USER', 'postgres'),
        'PASSWORD': os.getenv('ADMIN_DB_PASSWORD', 'bikeshop'),
        'HOST': 'postgres-admin-service.app-system.svc.cluster.local',
        'ENGINE': 'django.db.backends.postgresql',
        'PORT': '5432',
    },
    "ecomm_db": {
        'NAME': os.getenv('USER_DB_NAME', 'bikeshop'),
        'USER': 'postgres',
        'PASSWORD': os.getenv('USER_DB_PASSWORD', 'bikeshop'),
        'HOST': 'postgres-user-service.app-system.svc.cluster.local',
        'ENGINE': 'django.db.backends.postgresql',
        'PORT': '5432',

    }
}

# DATABASES = {
#     'admin_db': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'admin'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', 'bikeshop'),
#         'HOST': 'postgres-admin-service.app-system.svc.cluster.local',
#         'PORT': os.getenv('DB_PORT', '5432'),
#     },
#     "ecomm_db": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME', 'bikeshop'),
#         'USER': os.getenv('DB_USER', 'postgres'),
#         'PASSWORD': os.getenv('DB_PASSWORD', 'bikeshop'),
#         'HOST': 'postgres-user-service.app-system.svc.cluster.local',
#         'PORT': os.getenv('DB_PORT', '5432'),
#     }
# }

# "ecomm_db": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'bikeshop',
#         'USER': 'postgres',
#         'PASSWORD': 'bikeshop',
#         'HOST': 'postgres_user',
#         'PORT': '5432',
#     }
DATABASES['default'] = DATABASES['admin_db']
