"""
Django settings for ecomm project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-n7+!kp5_0edbiii%gly(y0)od=b08_$e6g$gq)i$q6wf6iba_0'

DEBUG = True

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'adminservice.app.apps.AdminServiceAppConfig',
    'ecomm.main_app.apps.EcommAppConfig',
    'storages',
]


DATABASES = {
    'admin_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'admin-app',
        'USER': 'postgres',
        'PASSWORD': 'itB{V-~G>Zyq^]\R',
        'HOST': '/cloudsql/main_app-integration-435314:europe-central2:admin-app',
        'PORT': '15432',
    },
    "ecomm_db": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'page-app',
        'USER': 'postgres',
        'PASSWORD': 'ke{,I4JEe+tZFM33',
        'HOST': '/cloudsql/main_app-integration-435314:europe-central2:page-app',
        'PORT': '15433',
    }
}

# "ecomm_db": {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'bikeshop',
#         'USER': 'postgres',
#         'PASSWORD': 'bikeshop',
#         'HOST': 'postgres_user',
#         'PORT': '5432',
#     }
DATABASES['default'] = DATABASES['admin_db']
