apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: kafka-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONPATH
          value: "/app:/app/admin_app:/app/ecomm"
        - name: DJANGO_SETTINGS_MODULE
          value: "kafka_consumer_settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        command: [ "python", "kafka_consumer.py" ]

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
  namespace: app-system
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-consumer