apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: gcr.io/app-integration-435314/kafka-consumer-image:latest
        imagePullPolicy: Always
        env:
        - name: PYTHONPATH
          value: "/app:/app/admin_app:/app/ecomm"
        - name: DJANGO_SETTINGS_MODULE
          value: "kafka_consumer_settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        volumeMounts:
        - name: gcp-credentials
          mountPath: /config
          readOnly: true
        command: [ "python", "kafka_consumer.py" ]
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
