version: "3.9"

services:
  postgres_user:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
    command: "/cloud_sql_proxy -instances=app-integration-435314:europe-central2:page-app=tcp:5433 -credential_file=/config/credentials.json"
    volumes:
      - C:/Users/Pepik/Desktop:/config
    ports:
      - "5433:5433"
    networks:
      - my_network

  user_app:
    build:
      context: ./ecomm
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./ecomm:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgres_user
      - kafka
    networks:
      - my_network
