FROM python:3.9-slim
WORKDIR /app
COPY ./ecomm /app
COPY ./ecomm/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .
ENV DJANGO_SETTINGS_MODULE=ecomm.settings
EXPOSE 8001
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]