FROM python:3.9-slim
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ENV DJANGO_SETTINGS_MODULE=ecomm.ecomm.settings
EXPOSE 8001
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]