apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-main-app
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-main-app
  template:
    metadata:
      labels:
        app: user-main-app
    spec:
      containers:
      - name: user-main-app
        image: user-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: DJANGO_SETTINGS_MODULE
          value: "ecomm.ecomm.settings"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "bikeshop"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "bikeshop"
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app-system
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: user-main-app
