apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: dolbyan/Python/ecomm:latest
        ports:
        - containerPort: 8001
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "ecomm.ecomm.settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8001
  selector:
    app: user-app
  type: LoadBalancer