apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-main-app
  template:
    metadata:
      labels:
        app: user-main-app
    spec:
      containers:
      - name: user-main-app
        image: gcr.io/app-integration-435314/user-app-image:latest
        ports:
        - containerPort: 8001
        command: ["gunicorn", "--bind", "0.0.0.0:8001", "ecomm.wsgi:application"]
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: DJANGO_SETTINGS_MODULE
          value: "ecomm.settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8001
  selector:
    app: user-main-app
  type: LoadBalancer