apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-main-app
  template:
    metadata:
      labels:
        app: admin-main-app
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: admin-main-app
          image: gcr.io/app-integration-435314/admin-app-image:latest
          ports:
          - containerPort: 8000
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: DB_HOST
            value: "34.118.110.89"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "admin-app"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcp-credentials
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    iam.gke.io/gcp-service-account: your-service-account@app-integration-435314-441618.iam.gserviceaccount.com