apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-main-app
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-main-app
  template:
    metadata:
      labels:
        app: admin-main-app
    spec:
      containers:
      - name: admin-main-app
        image: admin-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: DJANGO_SETTINGS_MODULE
          value: "admin_app.eshop.settings"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DB_HOST
          value: "postgres-admin-service"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: app-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: admin-main-app
