apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-main-app
  template:
    metadata:
      labels:
        app: admin-main-app
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command: [ "/cloud_sql_proxy",
                     "-instances=app-integration-435314:europe-central2:admin-app=tcp:5432",
                     "-credential_file=/secrets/gcp-credentials/credentials.json" ]
          volumeMounts:
            - name: gcp-credentials
              mountPath: /secrets/gcp-credentials
              readOnly: true

        - name: admin-main-app
          image: gcr.io/app-integration-435314/admin-app-image:latest
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_NAME
              value: "admin-app"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

volumes:
  - name: gcp-credentials
    secret:
      secretName: gcp-credentials
