apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-main-app
  template:
    metadata:
      labels:
        app: admin-main-app
    spec:
      containers:
      - name: admin-main-app
        image: gcr.io/app-integration-435314-441618/admin-app-image:latest
        ports:
        - containerPort: 8000
        command: ["gunicorn", "--workers", "4", "--threads", "2", "--bind", "0.0.0.0:8000", "admin_app.eshop.wsgi:application"]
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: DJANGO_SETTINGS_MODULE
          value: "admin_app.eshop.settings"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DB_HOST
          value: "34.118.110.89"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "admin-app"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: static-files
          mountPath: /app/static
      volumes:
      - name: static-files
        emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: admin-main-app
