apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-main-app
  template:
    metadata:
      labels:
        app: admin-main-app
    spec:
      containers:
        - name: admin-main-app
          image: gcr.io/app-integration-435314/admin-app-image:latest
          ports:
          - containerPort: 8000
          env:
          - name: PYTHONPATH
            value: "/app"
          - name: DJANGO_SETTINGS_MODULE
            value: "admin_app.eshop.settings"
          - name: KAFKA_BROKER_URL
            value: "kafka:9092"
          - name: DB_NAME
            value: "admin-app"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          volumeMounts:
          - name: gcp-credentials
            mountPath: /config
            readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
    - port: 8000
  selector:
    app: admin-main-app
  type: NodePort