version: "3.9"

services:
  postgres_admin:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
    command: "/cloud_sql_proxy -instances=app-integration-435314:europe-central2:admin-app=tcp:5434 -credential_file=/config/credentials.json"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/credentials.json
    volumes:
      - /path/to/credentials:/config
    ports:
      - "5432:5432"
    networks:
      - my_network

  admin_app:
    build:
      context: ./admin_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./admin_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_admin
      - kafka
    networks:
      - my_network

