apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-admin
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-admin
  template:
    metadata:
      labels:
        app: postgres-admin
    spec:
      containers:
      - name: postgres-admin
        image: postgres:13
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: bikeshop
        - name: POSTGRES_DB
          value: admin
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-admin-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-admin-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-admin-service
  namespace: app-system
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-admin