apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-admin
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-admin
  template:
    metadata:
      labels:
        app: postgres-admin
    spec:
      containers:
      - name: postgres-admin
        image: postgres:13
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: ADMIN_DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-admin-service
  namespace: app-system
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    app: postgres-admin