apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
      - name: admin-app
        image: admin-app-image  # Upewnij się, że masz odpowiedni obraz Dockera
        ports:
        - containerPort: 8001
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "adminservice.settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
    - port: 8001
  selector:
    app: admin-app
