apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
      - name: admin-app
        image: gcr.io/app-integration-435314/admin-app-image:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "adminservice.eshop.settings"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  ports:
    - port: 8000
  selector:
    app: admin-app
  type: LoadBalancer