FROM python:3.9-slim
ENV DB_HOST=host.docker.internal
ENV DB_NAME=admin
ENV DB_USER=postgres
ENV DB_PASSWORD=bikeshop
WORKDIR /app
COPY . /app
RUN pip3 install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]