FROM python:3.9-slim
WORKDIR /app

# Skopiowanie całego katalogu adminservice do /app
COPY adminservice /app

# Skopiowanie pliku requirements.txt do bieżącego katalogu
COPY adminservice/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .
ENV DJANGO_SETTINGS_MODULE=adminservice.eshop.settings
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]