name: Local Minikube Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube with Custom Config
      run: |
        minikube start --driver=docker --kubernetes-version=v1.28.3 --dns-proxy=false --no-vtx-check --profile=minikube

    - name: Setup Minikube Context
      run: |
        minikube update-context
        kubectl config use-context minikube

    - name: Verify Minikube Status
      run: |
        minikube status

    - name: Build Docker Images
      run: |
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression
        docker build -t admin-app:latest -f ./admin_app/Dockerfile .
        docker build -t user-app:latest -f ./ecomm/Dockerfile .
        docker build -t kafka-consumer:latest -f ./Dockerfile .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f postgres-pvc.yaml -n app-system
        kubectl apply -f ./admin_app/postgres-admin-deployment.yaml -n app-system
        kubectl apply -f ./ecomm/postgres-user-deployment.yaml -n app-system
        kubectl apply -f ./kafka-deployment.yaml -n app-system
        kubectl apply -f ./kafka-consumer-deployment.yaml -n app-system
        kubectl apply -f ./admin_app/admin-deployment.yaml -n app-system
        kubectl apply -f ./ecomm/user-deployment.yaml -n app-system
        kubectl apply -f ./ingress.yaml -n app-system

    - name: Verify Deployment
      run: |
        kubectl get pods -n app-system -w
        kubectl get svc -n app-system