name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Log in to Google Container Registry
      run: gcloud auth configure-docker

    - name: Build and push admin app
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./admin_app/Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push user app
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./ecomm/Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-app-image:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-app-image:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push kafka consumer
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./kafka-consumer/Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/kafka-consumer-image:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/kafka-consumer-image:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials app-cluster --zone europe-west1-b --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update deployment images
      run: |
        kubectl set image deployment/admin-main-app admin-main-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:${{ github.sha }}
        kubectl set image deployment/user-main-app user-main-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-app-image:${{ github.sha }}
        kubectl set image deployment/kafka-consumer kafka-consumer=gcr.io/${{ secrets.GCP_PROJECT_ID }}/kafka-consumer-image:${{ github.sha }}

    - name: Verify deployments
      run: |
        kubectl rollout status deployment/admin-main-app
        kubectl rollout status deployment/user-main-app
        kubectl rollout status deployment/kafka-consumer