name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

#    - name: Set up Google Cloud CLI
#      uses: google-github-actions/setup-gcloud@v2
#      with:
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Log in to Google Container Registry
      run: |
        gcloud auth configure-docker

    - name: Build and push Docker image for admin-main_app
      run: |
        docker buildx build -f ./admin_app/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:latest

    - name: Build and push Docker image for user-main_app
      run: |
        docker buildx build -f ./ecomm/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-app-image:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-app-image:latest

    - name: Build and push Docker image for kafka-consumer
      run: |
        docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/kafka-consumer-image:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/kafka-consumer-image:latest
    - name: Check files in admin-app container
      run: docker run --rm gcr.io/${{ secrets.GCP_PROJECT_ID }}/admin-app-image:latest ls /app/admin_app


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'kubectl'

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials app-cluster --zone europe-west1-b --project app-integration-435314
    - name: Create GCP credentials file
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > gcp-credentials.json


    - name: Create Kubernetes secret
      run: |
        kubectl create secret generic gcp-credentials \
          --from-file=credentials.json=gcp-credentials.json --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Kubernetes manifests for admin-main_app
      run: |
        kubectl apply -f admin_app/admin-deployment.yaml

    - name: Apply Kubernetes manifests for user-main_app
      run: |
        kubectl apply -f ecomm/user-deployment.yaml

    - name: Apply Kubernetes manifests for kafka-consumer
      run: |
        kubectl apply -f kafka-consumer-deployment.yaml

    - name: Apply Kafka and Zookeeper manifests
      run: |
        kubectl apply -f kafka-deployment.yaml