name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: 1.34.0
        kubernetes-version: v1.27.3
        driver: docker

    - name: Get minikube status
      run: |
        minikube status
        kubectl get nodes

    - name: Build images
      run: |
        eval $(minikube docker-env)
        docker build -t admin-app:latest -f ./admin_app/Dockerfile .
        docker build -t user-app:latest -f ./ecomm/Dockerfile .
        docker build -t kafka-consumer:latest -f ./Dockerfile .

    - name: Enable and wait for Ingress
      run: |
        minikube addons enable ingress
        echo "Waiting for Ingress controller to be ready..."
        kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=300s

    - name: Create namespace and deploy infrastructure
      run: |
        kubectl create namespace app-system --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f kafka-deployment.yaml -n app-system
        kubectl wait --namespace app-system \
          --for=condition=ready pod \
          --selector=app=zookeeper \
          --timeout=180s
        kubectl wait --namespace app-system \
          --for=condition=ready pod \
          --selector=app=kafka \
          --timeout=180s

    - name: Forward PostgreSQL port
      run: |
        kubectl port-forward service/postgres-admin-service 5432:5432 -n app-system &
        kubectl port-forward service/postgres-user-service 5433:5432 -n app-system &
      shell: bash

    - name: Deploy applications
      run: |
        kubectl apply -f kafka-consumer-deployment.yaml -n app-system
        kubectl apply -f admin_app/admin-deployment.yaml -n app-system
        kubectl apply -f ecomm/user-deployment.yaml -n app-system
        kubectl wait --namespace app-system \
          --for=condition=available \
          --all deployments \
          --timeout=300s

    - name: Deploy Ingress
      run: |
        # Apply Ingress configuration
        kubectl apply -f ingress.yaml -n app-system
        
        echo "Waiting for Ingress to be ready..."
        sleep 30  # Give additional time for Ingress to stabilize

    - name: Verify deployment
      run: |
        echo "Checking pod status:"
        kubectl get pods -n app-system
        echo "Checking service status:"
        kubectl get services -n app-system
        echo "Checking ingress status:"
        kubectl get ingress -n app-system
        echo "Checking ingress-nginx pods:"
        kubectl get pods -n ingress-nginx

    - name: Show app URL
      run: |
        minikube service list -n app-system
        echo "Minikube IP: $(minikube ip)"
        echo "Access your application at: http://$(minikube ip)"